### ISSUE TITLE
TODO list: minor issues

### ISSUE THREAD

**Issue by yetanothercarbot** [yetanothercarbot/curious-block#2]
- [ ] Mapgen does not leave a free spot for player spawning
- [ ] Have a main menu rather than jumping directly into the game
- [ ] Add a pause menu rather than exiting when pressing escape.
